apiVersion: v2
name: rocketchat
description: Rocket.Chat
type: application
version: 1.0.0
appVersion: 3.1.1
sources:
  - https://github.com/pacroy/rocketchat
maintainers:
  - name: Par
    email: pacroy@gmail.com