apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ $.Values.appHost }}
    secretName: rocketchat
  rules:
  - host: {{ $.Values.appHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
          servicePort: 3000
