apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
  name: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
    spec:
      containers:
      - name: rocketchat
        image: rocketchat/rocket.chat:3.0.12
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3000
          name: rocketchat
        env:
        - name: MONGO_URL
          value: mongodb://{{ printf "%s-%s" $.Release.Name "mongo" }}:27017/rocketchat
        - name: ROOT_URL
          value: https://{{ printf "%s%s" "https://" ( required "appHost is required" $.Values.appHost ) }}
        - name: Accounts_UseDNSDomainCheck
          value: "True"
        - name: MONGO_OPLOG_URL
          value: mongodb://{{ printf "%s-%s" $.Release.Name "mongo" }}:27017/local?replSet=rs0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
  name: {{ printf "%s-%s" $.Release.Name "rocketchat" }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rocketchat
  type: ClusterIP
